# Basic Data Exploration

### Importing necessary libraries

#### The following code is written in Python 3.x. libraries provide pre-written functionally to perform necessary tasks

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
plt.style.use('ggplot')
import warnings
warnings.filterwarnings('ignore')

In [2]:
#Reading the Data
data = pd.read_csv('C:/Users/Public/Downloads/owid-covid-data.csv', header = 0, index_col = 0)

In [3]:
#Printing no. of rows and no. of columns of data
data.shape

(81905, 58)

In [4]:
#Printing top 5 rows
data.head()

,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
iso_code,,,,,,,,,,,,,,,,,,,,,
AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,0.026,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,0.026,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,0.026,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,0.026,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,0.026,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 81905 entries, AFG to ZWE
Data columns (total 58 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   continent                              77929 non-null  object
 1   location                               81905 non-null  object
 2   date                                   81905 non-null  object
 3   total_cases                            80087 non-null  float64
 4   new_cases                              80085 non-null  float64
 5   new_cases_smoothed                     79084 non-null  float64
 6   total_deaths                           70548 non-null  float64
 7   new_deaths                             70706 non-null  float64
 8   new_deaths_smoothed                    79084 non-null  float64
 9   total_cases_per_million                79653 non-null  float64
 10  new_cases_per_million                  79651 non-null  float64
 11  new_cases_smoothed_per_million         78655 non-null  float64
 12  total_deaths_per_million               70127 non-null  float64
 13  new_deaths_per_million                 70285 non-null  float64
 14  new_deaths_smoothed_per_million        78655 non-null  float64
 15  reproduction_rate                      66030 non-null  float64
 16  icu_patients                           8456 non-null   float64
 17  icu_patients_per_million               8456 non-null   float64
 18  hosp_patients                          10127 non-null  float64
 19  hosp_patients_per_million              10127 non-null  float64
 20  weekly_icu_admissions                  743 non-null    float64
 21  weekly_icu_admissions_per_million      743 non-null    float64
 22  weekly_hosp_admissions                 1240 non-null   float64
 23  weekly_hosp_admissions_per_million     1240 non-null   float64
 24  new_tests                              37654 non-null  float64
 25  total_tests                            37363 non-null  float64
 26  total_tests_per_thousand               37363 non-null  float64
 27  new_tests_per_thousand                 37654 non-null  float64
 28  new_tests_smoothed                     43073 non-null  float64
 29  new_tests_smoothed_per_thousand        43073 non-null  float64
 30  positive_rate                          41415 non-null  float64
 31  tests_per_case                         40823 non-null  float64
 32  tests_units                            44484 non-null  object
 33  total_vaccinations                     7673 non-null   float64
 34  people_vaccinated                      7000 non-null   float64
 35  people_fully_vaccinated                5031 non-null   float64
 36  new_vaccinations                       6520 non-null   float64
 37  new_vaccinations_smoothed              12240 non-null  float64
 38  total_vaccinations_per_hundred         7673 non-null   float64
 39  people_vaccinated_per_hundred          7000 non-null   float64
 40  people_fully_vaccinated_per_hundred    5031 non-null   float64
 41  new_vaccinations_smoothed_per_million  12240 non-null  float64
 42  stringency_index                       69674 non-null  float64
 43  population                             81380 non-null  float64
 44  population_density                     76277 non-null  float64
 45  median_age                             73893 non-null  float64
 46  aged_65_older                          73047 non-null  float64
 47  aged_70_older                          73478 non-null  float64
 48  gdp_per_capita                         74212 non-null  float64
 49  extreme_poverty                        50590 non-null  float64
 50  cardiovasc_death_rate                  74843 non-null  float64
 51  diabetes_prevalence                    75854 non-null  float64
 52  female_smokers                         58689 non-null  float64
 53  male_smokers                           57822 non-null  float64
 54  handwashing_facilities                 37582 non-null  float64
 55  hospital_beds_per_thousand             68348 non-null  float64
 56  life_expectancy                        77738 non-null  float64
 57  human_development_index                74741 non-null  float64
dtypes: float64(54), object(4)
memory usage: 36.9+ MB

### Handling Missing Values

In [6]:
#Check for missing values in any columns
data.isnull().sum()

continent                                 3976
location                                     0
date                                         0
total_cases                               1818
new_cases                                 1820
new_cases_smoothed                        2821
total_deaths                             11357
new_deaths                               11199
new_deaths_smoothed                       2821
total_cases_per_million                   2252
new_cases_per_million                     2254
new_cases_smoothed_per_million            3250
total_deaths_per_million                 11778
new_deaths_per_million                   11620
new_deaths_smoothed_per_million           3250
reproduction_rate                        15875
icu_patients                             73449
icu_patients_per_million                 73449
hosp_patients                            71778
hosp_patients_per_million                71778
weekly_icu_admissions                    81162
weekly_icu_admissions_per_million        81162
weekly_hosp_admissions                   80665
weekly_hosp_admissions_per_million       80665
new_tests                                44251
total_tests                              44542
total_tests_per_thousand                 44542
new_tests_per_thousand                   44251
new_tests_smoothed                       38832
new_tests_smoothed_per_thousand          38832
positive_rate                            40490
tests_per_case                           41082
tests_units                              37421
total_vaccinations                       74232
people_vaccinated                        74905
people_fully_vaccinated                  76874
new_vaccinations                         75385
new_vaccinations_smoothed                69665
total_vaccinations_per_hundred           74232
people_vaccinated_per_hundred            74905
people_fully_vaccinated_per_hundred      76874
new_vaccinations_smoothed_per_million    69665
stringency_index                         12231
population                                 525
population_density                        5628
median_age                                8012
aged_65_older                             8858
aged_70_older                             8427
gdp_per_capita                            7693
extreme_poverty                          31315
cardiovasc_death_rate                     7062
diabetes_prevalence                       6051
female_smokers                           23216
male_smokers                             24083
handwashing_facilities                   44323
hospital_beds_per_thousand               13557
life_expectancy                           4167
human_development_index                   7164
dtype: int64

In [7]:
#Replacing null values with O
data.fillna(value = 0, inplace = True)

In [8]:
data.head()

,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
iso_code,,,,,,,,,,,,,,,,,,,,,
AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,0.0,0.0,0.0,0.0,0.026,...,1803.987,0.0,597.029,9.59,0.0,0.0,37.746,0.5,64.83,0.511
AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,0.0,0.0,0.0,0.0,0.026,...,1803.987,0.0,597.029,9.59,0.0,0.0,37.746,0.5,64.83,0.511
AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,0.0,0.0,0.0,0.0,0.026,...,1803.987,0.0,597.029,9.59,0.0,0.0,37.746,0.5,64.83,0.511
AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,0.0,0.0,0.0,0.0,0.026,...,1803.987,0.0,597.029,9.59,0.0,0.0,37.746,0.5,64.83,0.511
AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,0.0,0.0,0.0,0.0,0.026,...,1803.987,0.0,597.029,9.59,0.0,0.0,37.746,0.5,64.83,0.511

In [9]:
data.isnull().sum()

continent                                0
location                                 0
date                                     0
total_cases                              0
new_cases                                0
new_cases_smoothed                       0
total_deaths                             0
new_deaths                               0
new_deaths_smoothed                      0
total_cases_per_million                  0
new_cases_per_million                    0
new_cases_smoothed_per_million           0
total_deaths_per_million                 0
new_deaths_per_million                   0
new_deaths_smoothed_per_million          0
reproduction_rate                        0
icu_patients                             0
icu_patients_per_million                 0
hosp_patients                            0
hosp_patients_per_million                0
weekly_icu_admissions                    0
weekly_icu_admissions_per_million        0
weekly_hosp_admissions                   0
weekly_hosp_admissions_per_million       0
new_tests                                0
total_tests                              0
total_tests_per_thousand                 0
new_tests_per_thousand                   0
new_tests_smoothed                       0
new_tests_smoothed_per_thousand          0
positive_rate                            0
tests_per_case                           0
tests_units                              0
total_vaccinations                       0
people_vaccinated                        0
people_fully_vaccinated                  0
new_vaccinations                         0
new_vaccinations_smoothed                0
total_vaccinations_per_hundred           0
people_vaccinated_per_hundred            0
people_fully_vaccinated_per_hundred      0
new_vaccinations_smoothed_per_million    0
stringency_index                         0
population                               0
population_density                       0
median_age                               0
aged_65_older                            0
aged_70_older                            0
gdp_per_capita                           0
extreme_poverty                          0
cardiovasc_death_rate                    0
diabetes_prevalence                      0
female_smokers                           0
male_smokers                             0
handwashing_facilities                   0
hospital_beds_per_thousand               0
life_expectancy                          0
human_development_index                  0
dtype: int64

In [10]:
data.to_csv('C:/Users/Public/Downloads/cleaned-covid-data.csv', header = True, index = True)

### Handling Duplicate Records

In [11]:
#Check for duplicate data
duplicate = data.duplicated()
print(duplicate.sum())
data[duplicate]

0

Empty DataFrame
Columns: [continent, location, date, total_cases, new_cases, new_cases_smoothed, total_deaths, new_deaths, new_deaths_smoothed, total_cases_per_million, new_cases_per_million, new_cases_smoothed_per_million, total_deaths_per_million, new_deaths_per_million, new_deaths_smoothed_per_million, reproduction_rate, icu_patients, icu_patients_per_million, hosp_patients, hosp_patients_per_million, weekly_icu_admissions, weekly_icu_admissions_per_million, weekly_hosp_admissions, weekly_hosp_admissions_per_million, new_tests, total_tests, total_tests_per_thousand, new_tests_per_thousand, new_tests_smoothed, new_tests_smoothed_per_thousand, positive_rate, tests_per_case, tests_units, total_vaccinations, people_vaccinated, people_fully_vaccinated, new_vaccinations, new_vaccinations_smoothed, total_vaccinations_per_hundred, people_vaccinated_per_hundred, people_fully_vaccinated_per_hundred, new_vaccinations_smoothed_per_million, stringency_index, population, population_density, median_age, aged_65_older, aged_70_older, gdp_per_capita, extreme_poverty, cardiovasc_death_rate, diabetes_prevalence, female_smokers, male_smokers, handwashing_facilities, hospital_beds_per_thousand, life_expectancy, human_development_index]
Index: []

[0 rows x 58 columns]